#pragma once
#define MODOBJ_MESH_CBOX 100
#define MODOBJ_SCALE_TXT 101
#define MODOBJ_SCALE_SLIDER 102
#define MODOBJ_VELOC_TXT 103
#define MODOBJ_VELOC_SLIDER 104
#define MODOBJ_ROTX_TXT 105
#define MODOBJ_ROTX_SLIDER 106
#define MODOBJ_OBJNO_TXT 107

#define IDC_STATIC	-1
